### ISSUE TITLE
App crash during json serialization of notification options

### ISSUE THREAD

**Issue by jon-henry-citi** [symphonyoss/SFE-Minuet-DesktopClient#113]
The entire paragon crashes when JSON serialization fails due to incorrect field type in JSON structure.
In the example below Menuit will crash because title field is expecting a string but is receiving an array. An error should be returned instead of entire paragon.exe shutting down.

```javascript
var notificationOptions = {
message: "myNotification",
title: ["test"],
backgroundColor: "505050",
blinkColor: "ffa500",
isClickable: !0,
isPersistent: !0
};

paragon.notifications.create(notificationOptions, function(notificationId) {
            console.log('This example will crash paragon.exe');
        })
```

**Comment by lneir** [comment]
@rbarros-daitan can you please take a look?

**Comment by rbarros-daitan** [comment]
Current code do not validate the notificationOptions parameter. My point is: should it validates this parameter?
If so, is it enough to return null in case of wrong parameter, as if user is set in "dnd" mode?

**Comment by lneir** [comment]
just prevent the crash where it is occurring and add a log message to indicate issue.

**Comment by rbarros-daitan** [comment]
code fixed.

**Comment by lneir** [comment]
thanks, can you also create a jira ticket so we can track and get qa to test?

**Comment by lneir** [comment]
will be release in s44, jira ticket: https://perzoinc.atlassian.net/browse/DES-12428
