### ISSUE TITLE
Remove Symphony Package from Minuet Repo

### ISSUE THREAD

**Issue by gareth-gs** [symphonyoss/SFE-Minuet-DesktopClient#51]
The Symphony package code should be moved into it's own seperate repo

**Comment by lneir** [comment]
@gareth-gs Hi Gareth, before moving stuff to the new repo.  I have two PRs I want to get merged into dev.  @mattharper is supposed to review this evening and hopefully have them merged to dev tonight.  then you'll need to redo you delete PR and copy the latest over to new repo.  Sorry but want to get these in before we explode things.

**Comment by gareth-gs** [comment]
ok no problem.  Let me know when these are done.  I'll focus on the docs in that case.

**Comment by lneir** [comment]
stuff has been merged.  you can go ahead and move stuff to new repo.  i will close current delete pr, as you'll need to re-open with new stuff to delete.  thanks.

**Comment by lneir** [comment]
hold off again, one more change.  i'll let you know.  bug fix.

**Comment by lneir** [comment]
all commits are in, you are good to go.
