### ISSUE TITLE
Remove code referencing internal paths

### ISSUE THREAD

**Issue by gareth-gs** [symphonyoss/SFE-Minuet-DesktopClient#73]
Remove references to internal paths and replace internal branding with Minuet

**Comment by ghost** [comment]
@gareth-gs Will fixing this bug also ensure the following is changed?
./minuet/Paragon.Runtime/Kernel/Applications/ApplicationMetadata.cs:                        using( RegistryKey key = Registry.CurrentUser.OpenSubKey("Software\Policies\**Goldman Sachs**\DashNative\DevelperAccess") )
